#!/bin/sh

ovs-ofctl add-flow "priority=2, in_port=1,dl_dst=0xffffffffffff   action=output:2"
ovs-ofctl add-flow "priority=2, in_port=2,dl_dst=0xffffffffffff   action=output:1"

ovs-ofctl add-flow "priority=2, in_port=1,dl_type=0x800,ip_dscp=1 action=output:2"
ovs-ofctl add-flow "priority=1, in_port=1                         action=output:3"

ovs-ofctl add-flow "priority=0, action=output:1"
